# Generated by Django 4.2.1 on 2023-06-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Имя файла'),
        ),
    ]
