# Generated by Django 4.2.1 on 2023-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
